import type { Metadata } from "next";
import "./globals.css";
import "devextreme/dist/css/dx.material.blue.dark.css";

export const metadata: Metadata = {
  title: "Dx Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bodyClassName =
    "dx-viewport dx-device-desktop dx-device-generic dx-theme-material dx-theme-material-typography dx-color-scheme-blue-dark";

  return (
    <html lang="en">
      <body className={bodyClassName}>{children}</body>
    </html>
  );
}
