import type { Metadata } from "next";
import "./globals.css";
import "devextreme/dist/css/dx.material.blue.dark.css";

export const metadata: Metadata = {
  title: "Dx Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dx-viewport">{children}</body>
    </html>
  );
}
