import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "devextreme/dist/css/dx.material.blue.light.css";

const roboto = Roboto({ subsets: ["latin"], weight: '400' });

export const metadata: Metadata = {
  title: "Dx Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
